### ISSUE TITLE
what

### ISSUE THREAD

**Issue by 1000copy** [DreamingInBinary/Swiftjective-C#10]
Hey .What is meaning of "wrath of jetsam" in this sentence in your [article](https://www.swiftjectivec.com/optimizing-images/)

    "one` can gain some massive savings and forgo the unrelenting wrath of jetsam"

I have search in Google and Twitter and Slang Dictionary,I just get "Flotsam and Jetsam",but I can not get it.

**Comment by 1000copy** [comment]
Please, help me .What is meaning of "wrath of jetsam" in this sentence?
   "one can gain some massive savings and forgo the unrelenting wrath of jetsam"
I have search in Google and Twitter and Slang Dictionary,I just get "Flotsam and Jetsam",but I can not get it.

**Comment by DreamingInBinary** [comment]
@1000copy jetsam is what keeps memory under control on iOS, and what could boot your app if it hogs to much of it. [Here](https://www.quora.com/What-is-the-iOS-jetsam-and-how-does-it-exactly-work) is a good overview of it.
