### ISSUE TITLE
LinkPresentation preview not loading until view refresh in SwiftUI

### ISSUE THREAD

**Issue by mralexhay** [DreamingInBinary/Swiftjective-C#11]
Hi, loved your article on LinkPresentation, thanks!

I've got a small problem I wonder if you encountered:  using your code, the links load in a SwiftUI modal view (as per the image below), they visibly load the metadata as a small link view but don't show any of the thumbnails etc until the device is rotated (presumably refreshing the view). 

Is there a way to automatically refresh the view once the metadata has been fully downloaded? Perhaps tying it to a Binding or something?

Stil getting my head around SwiftUI!

Thanks again

![IMG_2991](https://user-images.githubusercontent.com/49391054/65384555-a1ce0600-dd1b-11e9-83eb-2120170d2432.PNG)

![IMG_2992](https://user-images.githubusercontent.com/49391054/65384557-a4c8f680-dd1b-11e9-9017-6bb21a268595.PNG)

**Comment by DreamingInBinary** [comment]
You probably need to call `sizeToFit` once you have the data 👍

**Comment by DreamingInBinary** [comment]
Sounds like you need to have the view resize when it loads (in UIKit sizeThatFits etc). Regardless,  thanks for opening an issue! These issues are more catered towards fixes or mistakes in articles.
