### ISSUE TITLE
LPMetaDataProvider called on main thread

### ISSUE THREAD

**Issue by inPhilly** [DreamingInBinary/Swiftjective-C#12]
I enjoyed your article. Wanted to post a question I had here. LPMetadataProvider needs to be called on the main thread and instantiates a WKWebview each time it is called (though we don’t see the WKWebview, and though the LPMetadataProvider returns on a background thread). This makes using LPLinkView with LPLinkMetatdata retrieved from LPMetadataProvider nearly impossible in a UITableView or UICollectionView that has over, say 50, cells that may be rapidly scrolled through. Assuming that the metadata is not cached on the first try, quick scrolling would grind the app to a halt because LPMetadataProvider does not truly work in the background. I wanted to get your thoughts on this.

This article may explain a little better what I am trying to say:
https://weiran.co/blog/2019/7/thumbnails-ios/

There is very little data on this subject on the web, and there are no successful examples of implementations of LPLinkView in UITableView or UICollectionView, where metadata must be fetched, to be found anywhere. Can this even be done successfully given the limitations of LPMetadataProvider?

**Comment by DreamingInBinary** [comment]
I'll take a look sometime this week - I've personally only used it in SwiftUI thus far.

**Comment by DreamingInBinary** [comment]
I've had this a question a few times now,  it's something to look into but unfortunately I'm not sure I'll ever get around to it.

**Comment by Isuru-Nanayakkara** [comment]
Hi @inPhilly, were you able to find anything new regarding improving the performance when using `LPMetadataProvider`? 

I tried using a vertical stack to display a list of links and it works a lot better than a table view. 

However if I start scrolling up and down as soon as the view loads, then the app crashes.

[Demo Project](https://www.dropbox.com/s/9o55s09z46fptmd/previewlistdemo.zip?dl=0)
