### ISSUE TITLE
Problems with image processing speed

### ISSUE THREAD

**Issue by SmiliPRO** [DreamingInBinary/Swiftjective-C#14]
Hi! First of all, thank you very much for your article about Optimizing Images... it was really interesting for me!

But I have some problems creating an app based on filtering images. Let me show you my code about some preset filters.

The next filter it's working fine and it takes around 3 second processing on my simulator so it's pretty good:

`
func liaFilter() -> UIImage? {
        let inImage = CIImage (image: self)
        
        dynamic let brightMatrix = CIFilter (name: "CIColorMatrix")
        dynamic let satMatrix = CIFilter (name: "CIColorMatrix")
        dynamic let expoMatrix = CIFilter (name: "CIColorMatrix")
        
        let SRGBImage = inImage?.applyingFilter("CILinearToSRGBToneCurve")
        
        brightMatrix?.setValue(SRGBImage, forKey: kCIInputImageKey)
        brightMatrix?.setValue(CIVector (x: 1, y: 0, z: 0, w: 0), forKey: "inputRVector")
        brightMatrix?.setValue(CIVector (x: 0, y: 1, z: 0, w: 0), forKey: "inputGVector")
        brightMatrix?.setValue(CIVector (x: 0, y: 0, z: 1, w: 0), forKey: "inputBVector")
        brightMatrix?.setValue(CIVector (x: 0, y: 0, z: 0, w: 1), forKey: "inputAVector")
        brightMatrix?.setValue(CIVector (x: 14.0/255.0, y: 14.0/255.0, z: 14.0/255.0, w: 0), forKey: "inputBiasVector")
        let brightImage = brightMatrix?.outputImage
        
        satMatrix?.setValue(brightImage, forKey: kCIInputImageKey)
        satMatrix?.setValue(CIVector (x: 0.682, y: 0.280, z: 0.038, w: 0), forKey: "inputRVector")
        satMatrix?.setValue(CIVector (x: 0.142, y: 0.820, z: 0.038, w: 0), forKey: "inputGVector")
        satMatrix?.setValue(CIVector (x: 0.142, y: 0.280, z: 0.578, w: 0), forKey: "inputBVector")
        satMatrix?.setValue(CIVector (x: 0, y: 0, z: 0, w: 1), forKey: "inputAVector")
        let satImage = satMatrix?.outputImage
        
        expoMatrix?.setValue(satImage, forKey: kCIInputImageKey)
        expoMatrix?.setValue(CIVector (x: 1.2, y: 0, z: 0, w: 0), forKey: "inputRVector")
        expoMatrix?.setValue(CIVector (x: 0, y: 1.2, z: 0, w: 0), forKey: "inputGVector")
        expoMatrix?.setValue(CIVector (x: 0, y: 0, z: 1.2, w: 0), forKey: "inputBVector")
        expoMatrix?.setValue(CIVector (x: 0, y: 0, z: 0, w: 1), forKey: "inputAVector")
        let expoImage = expoMatrix?.outputImage
        
        let linearImage = expoImage?.applyingFilter("CISRGBToneCurveToLinear")
        
        let cgImage = CIContext().createCGImage(linearImage!, from: linearImage!.extent)
        return UIImage (cgImage: cgImage!)
    }
`

But the problem comes when I use this other preset which takes around 14 second processing the image before presenting on the UIImageView... and that's too much for any user!

`
func nalaFilter() -> UIImage? {
        let inImage = CIImage (image: self)

        dynamic let contMatrix = CIFilter (name: "CIColorMatrix")
        dynamic let satMatrix = CIFilter (name: "CIColorMatrix")
        dynamic let brightMatrix = CIFilter (name: "CIColorMatrix")
        
        let SRGBImage = inImage?.applyingFilter("CILinearToSRGBToneCurve")
        
        contMatrix?.setValue(SRGBImage, forKey: kCIInputImageKey)
        contMatrix?.setValue(CIVector (x: 1.19, y: 0, z: 0, w: 0), forKey: "inputRVector")
        contMatrix?.setValue(CIVector (x: 0, y: 1.19, z: 0, w: 0), forKey: "inputGVector")
        contMatrix?.setValue(CIVector (x: 0, y: 0, z: 1.19, w: 0), forKey: "inputBVector")
        contMatrix?.setValue(CIVector (x: 0, y: 0, z: 0, w: 1), forKey: "inputAVector")
        contMatrix?.setValue(CIVector (x: -12.065/255.0, y: -12.065/255.0, z: -12.065/255.0, w: 0), forKey: "inputBiasVector")
        let contImage = contMatrix?.outputImage
        
        satMatrix?.setValue(contImage, forKey: kCIInputImageKey)
        satMatrix?.setValue(CIVector (x: 1.560, y: -0.494, z: -0.066, w: 0), forKey: "inputRVector")
        satMatrix?.setValue(CIVector (x: -0.250, y: 1.316, z: -0.066, w: 0), forKey: "inputGVector")
        satMatrix?.setValue(CIVector (x: -0.250, y: -0.494, z: 1.744, w: 0), forKey: "inputBVector")
        satMatrix?.setValue(CIVector (x: 0, y: 0, z: 0, w: 1), forKey: "inputAVector")
        let satImage = satMatrix?.outputImage
        
        brightMatrix?.setValue(satImage, forKey: kCIInputImageKey)
        brightMatrix?.setValue(CIVector (x: 1, y: 0, z: 0, w: 0), forKey: "inputRVector")
        brightMatrix?.setValue(CIVector (x: 0, y: 1, z: 0, w: 0), forKey: "inputGVector")
        brightMatrix?.setValue(CIVector (x: 0, y: 0, z: 1, w: 0), forKey: "inputBVector")
        brightMatrix?.setValue(CIVector (x: 0, y: 0, z: 0, w: 1), forKey: "inputAVector")
        brightMatrix?.setValue(CIVector (x: 17.0/255.0, y: 17.0/255.0, z: 17.0/255.0, w: 0), forKey: "inputBiasVector")
        let brightImage = brightMatrix?.outputImage
        
        let linearImage = brightImage?.applyingFilter("CISRGBToneCurveToLinear")
        
        let cgImage = CIContext().createCGImage(linearImage!, from: linearImage!.extent)
        let inColorImage = UIImage (cgImage: cgImage!)
       
        let brownColor = UIColor (rgb: 0xDEB887)
        let colorRect = CGRect (origin: .zero, size: self.size)
        //Colored base
        UIGraphicsBeginImageContextWithOptions(colorRect.size, true, 0.0)
        brownColor.setFill()
        UIRectFill(colorRect)
        let brownColoredImage = UIGraphicsGetImageFromCurrentImageContext()
        //Colored image
        let brownContext = UIGraphicsGetCurrentContext()
        brownContext!.setFillColor(UIColor.white.cgColor)
        brownContext!.fill(colorRect)
        inColorImage.draw(in: colorRect, blendMode: .normal, alpha: 1)
        brownColoredImage?.draw(in: colorRect, blendMode: .colorDodge, alpha: 1)
        let outBrown0Image = UIGraphicsGetImageFromCurrentImageContext()
        //Multiplied image
        inColorImage.draw(in: colorRect, blendMode: .normal, alpha: 1)
        outBrown0Image?.draw(in: colorRect, blendMode: .multiply, alpha: 1)
        let outBrownImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return outBrownImage
`

After reading your article I tried to use this alternative to colorize the image due to I guess this could be the slowest part:

`
        let renderer = UIGraphicsImageRenderer (bounds: colorRect)
        //Imagen coloreada
        let brownColoredImage = renderer.image { ctx in
            brownColor.setFill()
            ctx.cgContext.setFillColor(brownColor.cgColor)
        }
        //Imagen multiplicada
        let outbrown0Image = renderer.image { ctx in
            ctx.cgContext.setFillColor(UIColor.white.cgColor)
            ctx.fill(colorRect)
            inColorImage.draw(in: colorRect, blendMode: .normal, alpha: 1)
            brownColoredImage.draw(in: colorRect, blendMode: .colorDodge, alpha: 1)
        }
        let outBrownImage = renderer.image { ctx in
            inColorImage.draw(in: colorRect, blendMode: .normal, alpha: 1)
            outBrown0Image.draw(in: colorRect, blendMode: .multiply, alpha: 1)
        }
`

But it also takes around 14 second processing...

Do you have any idea about how can I get same result but with quicker process times?

Thank you in advance!

**Comment by DreamingInBinary** [comment]
Thanks for opening an issue! These issues are more catered towards fixes or mistakes in articles. I believe Mattt from NSHipster has an article covering image processing speeds that might be helpful.
