### ISSUE TITLE
Text in subscription textfield is almost invisible

### ISSUE THREAD

**Issue by haojianzong** [DreamingInBinary/Swiftjective-C#17]
I am on MacOS with Safari 13.1.1
<img width="569" alt="image" src="https://user-images.githubusercontent.com/4256824/84559153-fd896500-ad6a-11ea-86de-e5d2cac04e2b.png">

**Comment by DreamingInBinary** [comment]
Thanks for letting me know - that thing has been so hard to work with (it's from Mailchimp) and I'll see what I can do!

**Comment by DreamingInBinary** [comment]
This should be a non issue now!
