### ISSUE TITLE
"Solve for Happy" by Mo Gawdat

### ISSUE THREAD

**Issue by taxles** [DreamingInBinary/Swiftjective-C#23]
Dear Jordon,

I just came across your [Happy When?](https://www.swiftjectivec.com/happy-when/) post and sincerely hope your young daughter has improved for (as a parent) I know how painful it can be to have a young child in hospital.

I have something to add, and that is [Solve for Happy](https://www.solveforhappy.com/) by Mo Gawdat which really helped me understand what's involved in being happy.

I've raised this as an issue as suggested in your post.

Yours sincerely, AL.

**Comment by DreamingInBinary** [comment]
Thanks so much! I've added it to my to-read list!
