### ISSUE TITLE
uimenucontroller menu options don't show up on iOS 14 devices

### ISSUE THREAD

**Issue by PRK523** [DreamingInBinary/Swiftjective-C#25]
I have a collectionView, within which when i long press on each of the cell, i get the menu options like we see on UIPasteboard but this is a custom menu, but in my scenario when i change the orientation of ipad these options don't show up. The isMenuVisible bool property returns a false value. Can you please advice on this issue?

**Comment by DreamingInBinary** [comment]
Thanks for opening an issue! These issues are more catered towards fixes or mistakes in articles.
