### ISSUE TITLE
Swapped titles between Spotlight search code snippets

### ISSUE THREAD

**Issue by laurentboileau** [DreamingInBinary/Swiftjective-C#30]
Hi,

The post at https://www.swiftjectivec.com/spotlight-search-core-spotlight/ is titled "Spotlight Search using NSUserActivity" and includes a snippet that uses Core Spotlight APIs.

Similarly, the post at https://www.swiftjectivec.com/spotlight-search-user-activity/ is titled "Spotlight search using Core Spotlight" and includes a snippet that uses the NSUserActivity API.

Additionally, the code snippet for the Core Spotlight API post contains the following line twice:

```
let videogame = videogames.first!
```

Thanks for writing such a good resource. I often look up your best in class series.

Have a nice day.

**Comment by DreamingInBinary** [comment]
Great catch! Will patch that up!
