### ISSUE TITLE
Wrong size calculation in "Optimizing Images"

### ISSUE THREAD

**Issue by dcastil** [DreamingInBinary/Swiftjective-C#8]
I know this is a picky one, but I want to point it out as flakyness in this area led to some confusion when I started learning software development.

In your article you show this calculation:

> ```swift
> 1718 * 2048 * 4 / 1000000 = 14.07 megabytes give or take
> ```

But as 1 KB = 1024 B, the number 1000000 is misleading. It should be

```swift
1048576 = 1024 * 1024 = 2 ** 20
```

Then your calculation changes to

```swift
1718 * 2048 * 4 / 1024 / 1024 = 13.42 megabytes give or take
```

which also matches perfectly the outcome of 13.4 MB later in your article.

**Comment by DreamingInBinary** [comment]
Great catch @dcastil - feel free to open a PR and I'll get that out, or if not, no worries - I'll get it merged in later today 👍

**Comment by DreamingInBinary** [comment]
Fixed

**Comment by dcastil** [comment]
Ah you were obviously faster. 😊 Thanks for the fix! And also thanks for the great article!

**Comment by DreamingInBinary** [comment]
Absolutely, and thank you for making it even better! Cheers 🍻
